[build]
  # Base directory where the build command is executed
  base = "frontend"

  # Directory to publish (relative to base directory)
  publish = "."

  # Build command (empty for static files)
  command = ""

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# Simple redirect rules that preserve HTML file access
[[redirects]]
  # Handle API requests - redirect to your backend
  from = "/api/*"
  to = "https://smart-waste-management-production.up.railway.app/api/:splat"
  status = 200
  force = true

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Environment variables (for production)
[context.production.environment]
  NODE_ENV = "production"

# Environment variables (for branch deploys)
[context.branch-deploy.environment]
  NODE_ENV = "development"
