[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
  "npm ci --omit=dev --ignore-scripts"
]

[phases.build]
cmds = [
  "echo 'Build phase - No build needed for Node.js backend'"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
PORT = "8000"

[staticAssets]
"frontend" = "/"
